apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ml-api
spec:
  replicas: 4
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api
          image: kunj22/ml-api:v2
          ports:
            - containerPort: 80

